apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-devops-api
spec:
  selector:
    matchLabels:
      app: desafio-devops-api
  template:
    metadata:
      labels:
        app: desafio-devops-api
    spec:
      containers:
      - name: desafio-devops-api
        image: docker.io/library/desafio-devops-api:kind-v1
        imagePullPolicy: Never
        env:
        - name: NAME
          value: "Vinicius"
        resources:
          limits:
            cpu: "0.5"
            memory: "100Mi"
          requests:
            cpu: "0.5"
            memory: "50Mi"
        ports:
        - containerPort: 3000
